### ISSUE TITLE
Very high per-player outbound bandwidth on server

### ISSUE THREAD

**Issue by Blacksm1th** [NillerMedDild/Enigmatica2#149]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**

Running an Enigmatica 2 server on Ubuntu. Every player that joins consumes about 1.8Mbps of outbound bandwidth. Contrast that with a max of 500kbps with all other packs I've tried (All the mods 3, Direwolf20). I've replicated this running a server on my Windows PC as well. 

<img width="351" alt="enigmatica 2 high bandwidth" src="https://user-images.githubusercontent.com/5906402/47968306-50465b00-e025-11e8-9314-9c0878468e6d.png">

**Modpack Version**
1.51

**Additional Context**

**Comment by Blacksm1th** [comment]
I've isolated the issue to BetterQuesting, and have also confirmed that the Expert Mode pack has normal bandwidth consumption. Once I remove the three BetterQuesting-related mods, outbound bandwidth from the server drops dramatically.

**Comment by NillerMedDild** [comment]
I'll try to track down this quest(s) causing the issue, thank you for the report :)

**Comment by jinkhya** [comment]
Just adding my bit here, we're having the same issue on Enigmatica Expert actually. 
Here's what we did : 
- opened the server a week ago on 1.41, everything was fine
- updated to 1.42a, large bandwidth issues as described by blacksm1th
- downgraded to 1.41, back to fine.

When I tested disabling betterquesting mods on 1.42a, it solved the issue as well. 

As another test, on 1.42a version, I downgraded betterquesting back to 271 and it seemed to do a little better. Wich makes no sense regarding Blacksm1th post since Enigmatica normal has bq 271 in version 1.51...

If you need me to test something else, feel free to ask.

**Comment by NillerMedDild** [comment]
Thank you for your testing efforts @jinkhya :)

Does updating to the newest BQ help?

**Comment by jinkhya** [comment]
I can try it tonight after work :)

**Comment by NillerMedDild** [comment]
Thank you :)

**Comment by NillerMedDild** [comment]
Oh...right xD

**Comment by NillerMedDild** [comment]
Reported here: https://github.com/Funwayguy/BetterQuesting/issues/488

**Comment by NillerMedDild** [comment]
bump

**Comment by codeka** [comment]
This is still a big problem on the official server. It's completely unplayable with > 4 ppl online at once (tps is normal, but actions take 15+ seconds to register on the server)

Related to this, could we at least institute a "no afk" policy on the server? I haven't been able to play for a few days because there's to many players online.

**Comment by codeka** [comment]
FWIW, Funwayguy says on discord:

Notable bug fixes since then:
- 280 fixes party invites auto completing progression incorrectly and auto-claim quests being broken
- 281 fixed repeatable task resets being exploitable by changing dimension
- 282 huge improvements to the quest update caching and networking packet spam
- 285 even bigger improvements to quest ticking which should stop it tanking the TPS as much as it used to

**Comment by NillerMedDild** [comment]
I have been waiting for the initial rounds of bug fixes, I will be updating asap :)
