### ISSUE TITLE
Map reset

### ISSUE THREAD

**Issue by HooplaPrime** [NillerMedDild/Enigmatica2#22]
I've been playing this mod pack for about a week now and twice my worlds have been reset to where ALL my work was gone. Chests, smeltry, tables, etc... everything was completely gone.

**Comment by NillerMedDild** [comment]
The issue template is there for a reason, don't just delete it.

**Comment by HooplaPrime** [comment]
Wow talk about rude.

**Comment by HooplaPrime** [comment]
That was just plain rude. I'm glad I deleted the pack.

**Comment by Lukas45** [comment]
It's also very rude to delete the template that actually makes us able to try and fix your issue, instead of us having to re-ask everything the template would already tell you to include.

It's a waste of our time, and we have better things to do than to re-write an already written guide in 10 different comments, because you were too lazy to fill it out.

**Comment by HooplaPrime** [comment]
I was trying to report a bug with the pack, that the map for some reason
reset itself to where everything I had created in the world was erased. I
did not delete anything prior to the original post. But whatever I guess
most Danes are complete douches. Have a nice day, prick.
