### ISSUE TITLE
Quests not completing. (Mekanism - Part 1)

### ISSUE THREAD

**Issue by Specs4** [NillerMedDild/Enigmatica2#366]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes?

**Issue**
Quest Enriched Ores! and Powered Furnace I am unable to complete since 1.60 update. It might have been an issue with 1.59 as well as Enriched Ores! should have been completed as I did that before 1.60 update however, I stopped playing before I noticed it wasn't completed.

**Comment by NillerMedDild** [comment]
Are they crafting tasks?

**Comment by Specs4** [comment]
Yes, You just craft them at the crafting table once you have the required resources.

**Comment by NillerMedDild** [comment]
I'll rephrase. Are there icons of a furnace, crafting table and anvil in the top right of the quests you cannot complete?

**Comment by Specs4** [comment]
I forgot to explain that in my first post, no there are not any of those icons.

**Comment by NillerMedDild** [comment]
Oh, damn :P I'll look into it, thanks for the report.

**Comment by bonnedav** [comment]
Same. Mekanism quests all worked in 1.59 but none work in 1.60. I saw in changelog you switched to the jz fork of mek, might be the issue.

**Comment by NillerMedDild** [comment]
Yeah, maybe the fork enforces NBT tags or something.

**Comment by Semajor** [comment]
I would tend to agree with the suspicion that NBT enforcement is the culprit here based on what I've been seeing. I started fiddling with the tasks to see what shook out, and the problem appears to be with the groupDetect function on the retrieval tasks. Setting it to false will allow some of them to be completed, but it requires manually clicking the Detect/Submit button and disables the fanfare sound/display for quest completion.

A few of the machines (everything on the Metallurgic Infuser chain so far) also don't detect unless I go into the task and select the item in my own inventory, rather than using the search and selecting from the list on the right.

I also have a Precision Sawmill from a loot box reward that wasn't detected by the quest without disabling the groupDetect function, so something is definitely rotten in Denmark with regards to Mekanism and BQM detection.

**Comment by Specs4** [comment]
All the Basic quests under Mekanism Part 1 work besides Enriched Ores! (tested under 1.59)
