### ISSUE TITLE
Friend can’t complete any quests in LAN multiplayer

### ISSUE THREAD

**Issue by Dimentive** [NillerMedDild/Enigmatica2#373]
**Modpack version**
1.60

**Can the issue be reproduced?**
Unknown

**Issue**
I’m playing with a friend via LAN, and while I managed to unlock the first Tinker’s Construct quest (“Materials and You”) just fine, he can’t. He has made a Materials and You book and over eight blank patterns, but it still says incomplete, even after clicking “Detect/Submit.” The same happens with other quests he’s tried. He’s unlocked a few quests, but now, it seems as though he can’t complete any quests.

**Comment by NillerMedDild** [comment]
Quests don't work properly over LAN, sorry :/ a lot of things don't work well over LAN in fact, I highly recommend using a server.

**Comment by Dimentive** [comment]
Aww, that’s a shame. Is there no workaround? Should I contact the developer Better Questing?

**Comment by NillerMedDild** [comment]
No workaround that I know of, maybe the dev can prove me wrong :)

**Comment by Dimentive** [comment]
Well, that’s a shame. I’ll wait to see if Funwayguy can help me. If not, I’ll start using a server instead of playing via LAN, which is something I didn’t want to do since I have to download and maintain the server version of the modpack separately, as well as run a server on my computer.

If there’s no workaround, maybe the mod dev can incorporate a fix. That’d be fantastic.

**Comment by Funwayguy** [comment]
I'm currently testing this in LAN and struggling to recreate the conditions to break this. The only thing I've found so far is a minor issue with party member quest states not syncing immediately and sometimes requiring a manual detect but otherwise the progression of other members still counts. I'm thinking something may have messed up with the active quest cache making the tasks not actually listen to submissions which it thinks are locked.

**Comment by Dimentive** [comment]
@Funwayguy Oh, that’s interesting. Thanks for the response!
So, it’s not a definitive issue making quests unobtainable in LAN play?

Do you think this is something that you could fix in an update—or that I could fix by using a command?

**Comment by Dimentive** [comment]
@Funwayguy Oh, that’s interesting. Thanks for the response!
So, it’s not a definitive issue making quests unobtainable in LAN play?

Do you think this is something that you could fix in an update—or that I could fix by using a command?
If so, that would be greatly appreciated!

**Comment by Funwayguy** [comment]
Once I can recreate the issue in dev I'll be able to start debugging the root cause and put an update out for it but until then I have no idea what command would help resolve it. If it is indeed something to do with the quest caching then no command will help anyway because that's updated per-player on the fly.

Side note: This isn't the first report I've heard about this and it may not even be isolated to LAN but because I haven't been able to recreate either issue in dev I can't be definitively sure. Reaaaally hoping and crossing my fingers this doesn't turn out to be as evasive and as the database corruption bug.

**Comment by Dimentive** [comment]
All right. I hope you manage to fix it. My friend not being able to unlock any quests takes away a lot from the modpack. I’ve yet to try playing on a server instead of a LAN-enabled world, but if the issue may not be isolated to LAN play, I’m not sure if it’ll work. Still, I’ll try it tomorrow.

**Comment by Dimentive** [comment]
My friend managed to complete the quest “The Basics” in Mekanism Part 1, which required a few different items—as well as every quest that doesn’t require any item. However, he couldn’t complete Tinkers’ Construct quest (“Materials and You”) and the Actually Additions quest where you need a Coffee Maker.

So, some quests are obtainable for him while others are not, and every quest is obtainable for _me_, the host of the LAN world.

I’m not sure what’s causing this.

**Comment by Dimentive** [comment]
Shouldn’t the “not fixed” tag be changed?
