### ISSUE TITLE
Crash with Phosphor when starting server

### ISSUE THREAD

**Issue by Willsr71** [NillerMedDild/Enigmatica2#428]
**Modpack version**
1.64

**Can the issue be reproduced?**
unknown

**Logs**
https://hastebin.com/usucufijic.rb

**Issue**
Issue is currently tracked on Phosphor's tracker here: https://gitea.gildedgames.com/jellysquid/Phosphor/issues/18

**Comment by Discomanco** [comment]
The issue is Spongeforge not liking Phosphor, nothing we can do much about. You should be fine just removing Phosphor from the server, clients should still be able to connect

**Comment by phit** [comment]
For the record, this is Phosphors mod compatibility with sponge failing due to the user running an outdated Sponge version. Not Sponge's fault (or not liking Phosphor) at all, Phosphor simply lacked a version check in older versions to tell the user about it. This was fixed in later Phosphor versions https://github.com/jellysquid3/Phosphor/commit/4cfd8cf9fef0d07f3a12f574af4fac47a19e9406
