### ISSUE TITLE
Game crashed in midgame, can't log back on server.

### ISSUE THREAD

**Issue by Furree** [NillerMedDild/Enigmatica2#444]
**version number**
Input version here 1:65a

**Can the issue be reproduced?**
Yes/

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Input short description of the issue here
Game crashed midgame as I was going up on a elevator block. Fault msg:
The game crashed whilst unexpected error Error: java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to crazypants.enderio.base.power.forge.item.IInternalPoweredItem
I am not able to log back on the server (A Patrion SMP server) Mod on the server says that everything is good on the server.

[crash-2019-04-23_20.01.50-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/3108998/crash-2019-04-23_20.01.50-client.txt)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thanks for the report. The issue is the Building Wand you're holding, if you can edit it out of your player.data you should be fine. You could also remove the mod and readd it, that should do the trick as well.

It has been reported here:
https://github.com/portablejim/BetterBuildersWands/issues/101

**Comment by NillerMedDild** [comment]
This has been fixed for some time, as far as I can tell.
