### ISSUE TITLE
Having crashes after updating to 1.66

### ISSUE THREAD

**Issue by Ravalli03** [NillerMedDild/Enigmatica2#451]
**Modpack version**
1.66

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/2F8e2PTC

https://pastebin.com/NbW5sZux

**Issue**
After updating the pack from 1.65a to 1.66, the game crashes once I start playing. This has happened twice in a row.

Thanks for any help you could provide.

If this is a feature request, feel free to delete the template.

**Comment by Aeka80** [comment]
Posted about the same issue (#450) a few hours ago. The problem is with Wizardry 0.10.0 crashing when you use any scroll wheel functions. The Wizardry dev is aware, and for now its easiest to just downgrade it to v0.9.9. If you have a server you'll need to confirm the next start up since some items will be missing from the downgrade, other than that everything runs fine with this fix.
