### ISSUE TITLE
Using Exchanger on Mycelial Netherrack gives you Spectral Moss (Remove Exchangers)

### ISSUE THREAD

**Issue by mpavkovic** [NillerMedDild/Enigmatica2#539]
**Modpack version**
1.69b

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Using Exchanger on Mycelial Netherrack gives you Spectral Moss instead, which when broken with pickaxe drops End Stone, so it could be used as a potential exploit to get End Stone from Netherrack?

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I don't think this will ever be fixed I'm afraid, it has been a known issue for a long time by now.
https://github.com/JackyyTV/Exchangers/issues/60

I may just remove the mod.

**Comment by JackyyTV** [comment]
Just so you guys are aware, this was just fixed in [2.9](https://www.curseforge.com/minecraft/mc-mods/exchangers/files/2903998), I was unfortunately very very busy with work and had to keep delaying the update until now, but it's finally fixed. If you want to add the mod back in your pack, feel free to, but it's entirely up to you. I am sorry if I made anyone really frustrated about all these bugs.

**Comment by NillerMedDild** [comment]
Thanks for letting us know - No hard feelings at all, irl comes first of course. The main reason Exchanger was removed was because Building Gadgets could do the same, and a bit more, not because of bugs :)

**Comment by JackyyTV** [comment]
Yeah, I am aware that Building Gadgets has a lot of features overlapped with Exchangers, but it still exists for modpack makers that prefer to have linear progression on tools. That is one thing I dislike about Building Gadgets - it basicially removed that linear progression, some people do prefer it, but some don't. I am not really that fussed if people prefer Building Gadgets over Exchangers, but that's just my opinions on it.
