### ISSUE TITLE
Random game freezes 

### ISSUE THREAD

**Issue by MinLyp** [NillerMedDild/Enigmatica2#554]
**Modpack version**
1.70

**Can the issue be reproduced?**
unknown it's completely random

**Issue**
When I play with friends on my server
3 / 4 random players out of 6 persons gets random game freezes 
at this same time 
in different locations
doing different things
and after 30seconds "Java isn't responding"
but sometimes it unfreeze without crash 
 it's completely random and annoying :/

All of us have +6GB of RAM assigned to minecraft

**Comment by NillerMedDild** [comment]
With this little information, I can only guess. My guess is that they are using old Java.
This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
