### ISSUE TITLE
Better questing: Can't accept party invite

### ISSUE THREAD

**Issue by Chrissyboy70** [NillerMedDild/Enigmatica2#596]
**Modpack version**
Enigmatica 2 expert 1.74 and Enigmatica 2

**Issue**
When I invite one of my friends in my quest book they won't see my invitation. So they can't accept it.

**Comment by NillerMedDild** [comment]
Thanks for the report. This issue seems to happen a lot, but I was under the impression that it had been fixed.

Can your friend invite you instead? 
Is it a LAN world?

**Comment by NillerMedDild** [comment]
Thanks for the report. I thought this had been fixed.

Can your friend invite you?
Are you in a LAN world?

**Comment by Chrissyboy70** [comment]
it's a hosted server

he cannot invite me aswell

I reinstalled both the server and both clients

**Comment by NillerMedDild** [comment]
Alright, thank you. I'll look into it tomorrow evening :)

**Comment by NillerMedDild** [comment]
It took me a while, but I reported the issue :P

**Comment by Nutriii** [comment]
@NillerMedDild I was trying to track down this same issue on expert mode. I have only noticed the issue in this modpack (could be a sample size issue) and when party invites aren't working we have also been defaulted the Steve and Alex skins rather than our customs. We were thinking it was an issue with player profiles but are having a hard time narrowing it down further.

**Comment by Funwayguy** [comment]
My own testing revealed that it may have to do with expiry timestamps and system clocks between the client(s) and server being out by more than 60s. This would explain why I can never recreate it in dev and some players have no issue while for others it never works at all.

I have a fix in mind but it requires a small rewrite of how invites are issued between clients so that the server clock is the only one that is ever referenced.

**Comment by TInyTim917** [comment]
I would like to add to this discussion. My friend could add himself to the party, but he cannot see any of the quest i have completed.

**Comment by Jaymus3** [comment]
I can confirm through my own testing that updating system clocks to be very closely synced fixes the issue.  I used NetTime to sync the clocks on server and clients and suddenly party invites worked.
