### ISSUE TITLE
Client Crash when shift-clicking recipe with planks in AE2 terminal

### ISSUE THREAD

**Issue by TInyTim917** [NillerMedDild/Enigmatica2#604]
**Modpack version**
1.7.5b

**Issue**
When bring the recipe from JEI with the "+" button into a Crafting Monitor of AE2 I get disconnected from the server. The issue is repeatable.
![image](https://user-images.githubusercontent.com/57307059/72200573-2ce12200-3419-11ea-8c87-67668989cbaa.png)

**Comment by NillerMedDild** [comment]
Please supply your latest.log, you can find it in the logs folder of your Minecraft instance :)

**Comment by TInyTim917** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/4049090/latest.log)

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by NillerMedDild** [comment]
Please let me know if updating fixes the issue :)

**Comment by TInyTim917** [comment]
Updated Java, and did everything listed above. Still Crashed. 
Heres the Log
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/4050108/latest.log)

**Comment by NillerMedDild** [comment]
Cool, I'll look into it then :)

**Comment by Corruptedtouch** [comment]
I am also having this issue. Using Wireless Crafting Terminal. Also checked Java Version.

**Comment by lays24mc** [comment]
Hi,

I have the same problem. Not only with the signs, but also with jukeboxes, Treated Wood... The problem is not only with the wireless terminal, but also with the normal crafting terminal of Applied Energistics 2.

As soon as I remove the mods Forestry + Addons, this problem does not exist. After consulting the Discord #Support Channel it seems that there are too many wood variants sent, which the client can't handle.

I tried some things to solve the problem. Unfortunately I can't find a solution yet. I assume that the problem is with Forestry.

**Comment by Sensei1999** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/4222605/latest.log)
I'm having the same issue

**Comment by NillerMedDild** [comment]
Seems to be caused by JustEnoughEnergistics, atleast that's what I gathered from reading old issues on AE2 and JEE issue trackers.
I reported the bug here: https://github.com/p455w0rd/JustEnoughEnergistics/issues/15

**Comment by NillerMedDild** [comment]
I'm considering removing some planks from the oredict, that should fix the issue.
