### ISSUE TITLE
Modpack won't load crashes while trying to load JEI

### ISSUE THREAD

**Issue by patomartinsch** [NillerMedDild/Enigmatica2#636]
**Modpack version**
1.77

**Issue**
Modpack won't load

**Logs**
[crash-2020-03-06_12.14.40-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/4299733/crash-2020-03-06_12.14.40-client.txt)

**Comment by NillerMedDild** [comment]
You need to allocate at least 6GB of RAM (Check Twitch's Minecraft settings)

And while you're at it, your Java version is outdated. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
