### ISSUE TITLE
Free 'ghost' Item

### ISSUE THREAD

**Issue by XDelta** [NillerMedDild/Enigmatica2#637]
**Modpack version**
Enigmatica 2, 1.76
Java 1.8.0_231 64x

**Issue**
On 2 occasions, a "Middle Backpack" from the 'Backpack' mod appeared in the crafting result slot of the tinker crafting station, I was able to grab these items out and they stayed as an item. The backpacks both show 0/0 slots used in the tooltip, I don't know this backpack mod but looks like it requires making top and bottom parts neither of which I have made nor had the resources to put it together. 

There is an 'Actually Additions' small storage crate next to it on the right and a Thaumcraft research table on the left. Not sure how or why this occurred or how to replicate it, I'll shadowplay it if it happens again. 

This is a singleplayer world with cheats off.
There has been no modification to the pack or settings, everything is defaults.

**Comment by NillerMedDild** [comment]
We've seen that issue before, with the Thaumcraft crafting table. Please try moving the Crafting table away from the Thaumcraft one.

**Comment by XDelta** [comment]
Its the research table, but I'll move it anyway

**Comment by 51RB0B** [comment]
I can confirm this. I don't know how to consistently replicate it, it occurs rarely and very randomly. I don't have any Thaumcraft tables nearby, only a tinkerer's construct setup, a small storage crate, an engineer's table, and an astral sorcery grindstone. The Tinkerer's construct table only touches a stencil table and the small storage crate. I've had it happen twice today, nothing about the setup was changed since three days ago. I would open the tinkerer's table and see a "Middle Backpack" in the output slot. There was nothing in the crafting table at the time. The first time it happened, I took the backpack out. It stays in the storage crate where I put it even after a relog. I can't use the backpack, as it has no slots. The second time it happened, I closed the table and opened it again, and it had disappeared. The picture below is my setup, and the middle backpack in my hand.
![2020-08-03_15 30 24](https://user-images.githubusercontent.com/69171873/89230096-efeca080-d59f-11ea-8ae9-a2eceb5c1a85.png)
