### ISSUE TITLE
Gendustry crashes game while starting

### ISSUE THREAD

**Issue by Sushi4900** [NillerMedDild/Enigmatica2#71]
#### Issue Description
Crashes while loading up the game
#### Modpack version (Do not use "latest")
1.44
#### Crash Report

[crash-2018-08-16_17.54.17-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/2294339/crash-2018-08-16_17.54.17-client.txt)

**Comment by NillerMedDild** [comment]
This issue is present in nearly all modpacks, try this fix:
Step 1: File>Settings
Step 2: Minecraft Tab
Step 3: Scroll down to "Launch Method"
Step 4: Switch from "Native Launcher" to "Jar Launcher"
Step 5: Select the latest version of Java you have installed
Step 6: Log back into Minecraft with the old launcher
Step 7: Close the launcher because it will try to launch Vanilla 1.13
Step 8: Launch the modpack you were playing originally, it should all work now

**Comment by NillerMedDild** [comment]
You're welcome :)
